/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestURouteRouteImport } from './routes/_guest/u/route'
import { Route as AuthPreviewRouteRouteImport } from './routes/_auth/preview/route'
import { Route as AuthDashboardRouteRouteImport } from './routes/_auth/dashboard/route'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as AuthPreviewIndexRouteImport } from './routes/_auth/preview/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as GuestUUsernameRouteImport } from './routes/_guest/u/$username'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestURouteRoute = GuestURouteRouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthPreviewRouteRoute = AuthPreviewRouteRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardRouteRoute = AuthDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthPreviewIndexRoute = AuthPreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPreviewRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDashboardRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestUUsernameRoute = GuestUUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => GuestURouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/preview': typeof AuthPreviewRouteRouteWithChildren
  '/u': typeof GuestURouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/u/$username': typeof GuestUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/preview/': typeof AuthPreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/u': typeof GuestURouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/u/$username': typeof GuestUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/preview': typeof AuthPreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRouteRouteWithChildren
  '/_auth/preview': typeof AuthPreviewRouteRouteWithChildren
  '/_guest/u': typeof GuestURouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_guest/u/$username': typeof GuestUUsernameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/preview/': typeof AuthPreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/preview'
    | '/u'
    | '/login'
    | '/signup'
    | '/u/$username'
    | '/api/auth/$'
    | '/app/'
    | '/dashboard/'
    | '/preview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/u'
    | '/login'
    | '/signup'
    | '/u/$username'
    | '/api/auth/$'
    | '/app'
    | '/dashboard'
    | '/preview'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_auth/dashboard'
    | '/_auth/preview'
    | '/_guest/u'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_guest/u/$username'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/dashboard/'
    | '/_auth/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/u': {
      id: '/_guest/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof GuestURouteRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/preview': {
      id: '/_auth/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthPreviewRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/preview/': {
      id: '/_auth/preview/'
      path: '/'
      fullPath: '/preview/'
      preLoaderRoute: typeof AuthPreviewIndexRouteImport
      parentRoute: typeof AuthPreviewRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthDashboardRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest/u/$username': {
      id: '/_guest/u/$username'
      path: '/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof GuestUUsernameRouteImport
      parentRoute: typeof GuestURouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthDashboardRouteRouteChildren {
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
}

const AuthDashboardRouteRouteChildren: AuthDashboardRouteRouteChildren = {
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
}

const AuthDashboardRouteRouteWithChildren =
  AuthDashboardRouteRoute._addFileChildren(AuthDashboardRouteRouteChildren)

interface AuthPreviewRouteRouteChildren {
  AuthPreviewIndexRoute: typeof AuthPreviewIndexRoute
}

const AuthPreviewRouteRouteChildren: AuthPreviewRouteRouteChildren = {
  AuthPreviewIndexRoute: AuthPreviewIndexRoute,
}

const AuthPreviewRouteRouteWithChildren =
  AuthPreviewRouteRoute._addFileChildren(AuthPreviewRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthDashboardRouteRoute: typeof AuthDashboardRouteRouteWithChildren
  AuthPreviewRouteRoute: typeof AuthPreviewRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthDashboardRouteRoute: AuthDashboardRouteRouteWithChildren,
  AuthPreviewRouteRoute: AuthPreviewRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestURouteRouteChildren {
  GuestUUsernameRoute: typeof GuestUUsernameRoute
}

const GuestURouteRouteChildren: GuestURouteRouteChildren = {
  GuestUUsernameRoute: GuestUUsernameRoute,
}

const GuestURouteRouteWithChildren = GuestURouteRoute._addFileChildren(
  GuestURouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestURouteRoute: typeof GuestURouteRouteWithChildren
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestURouteRoute: GuestURouteRouteWithChildren,
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
